// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDK9ZNoKH1_gsoFhtsRbAKzKsHmAV7FC2s',
    appId: '1:544954505506:web:bc62f4341f17db8f226d7b',
    messagingSenderId: '544954505506',
    projectId: 'one-glance',
    authDomain: 'one-glance.firebaseapp.com',
    databaseURL: 'https://one-glance-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'one-glance.appspot.com',
    measurementId: 'G-XCZHP9VL9T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCefh7CV8jhUHL-T2V97lBGblMOGF7Ygmo',
    appId: '1:544954505506:android:a4a70feca9edc781226d7b',
    messagingSenderId: '544954505506',
    projectId: 'one-glance',
    databaseURL: 'https://one-glance-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'one-glance.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfs84IukavsgbwyXr6tjT5D9h5RExFmjs',
    appId: '1:544954505506:ios:4d6b67f3b9c47b29226d7b',
    messagingSenderId: '544954505506',
    projectId: 'one-glance',
    databaseURL: 'https://one-glance-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'one-glance.appspot.com',
    iosClientId: '544954505506-9m1udbgbulvrsd29s39h1kvl66qq8i61.apps.googleusercontent.com',
    iosBundleId: 'com.example.oneGlance',
  );
}
